language: bash
arch:
  - amd64
services:
  - docker
jobs:
  include:
    - stage: build branch
      script:
        - docker build -t chrisjohnson00/microservice_backend -f Dockerfile .
        - docker login --username=chrisjohnson00 --password=$DOCKER_HUB_PASSWORD
        - docker tag chrisjohnson00/microservice_backend chrisjohnson00/microservice_backend:$TRAVIS_BRANCH
        - docker push chrisjohnson00/microservice_backend:$TRAVIS_BRANCH
      if: tag is blank
    - stage: build tag
      script:
        - docker build -t chrisjohnson00/microservice_backend -f Dockerfile .
        - docker login --username=chrisjohnson00 --password=$DOCKER_HUB_PASSWORD
        - docker tag chrisjohnson00/microservice_backend chrisjohnson00/microservice_backend:$TRAVIS_TAG
        - docker push chrisjohnson00/microservice_backend:$TRAVIS_TAG
        - docker push chrisjohnson00/microservice_backend
      if: tag IS present
